### ISSUE TITLE
The anchor for gitlab URLs don't see to work properly.

### ISSUE THREAD

**Issue by letronje** [ben-gibson/GitLink#100]
**Describe the bug**
I use Gitlink with our Gitlab go repo and the link that opens up in the browser has an anchor of the form "#L111-L112" . This doesn't highlight the line. The anchor that works is "#L111-112" ( without the second L )

**To Reproduce**
1. Go to GoLand, right click and select 'Open in Github'
2. The URL opened in the browser ends with "#L111-L112"

**Expected behavior**
The URL opened in the browser should end with "#L111-112"

**Comment by ben-gibson** [comment]
Are you sure you have `GitLab` selected as your host in the plugin settings and not `GitHub`? It can't auto-detect the host you use so it will default to `GitHub`.
