### ISSUE TITLE
Permalink not working with Gerrit

### ISSUE THREAD

**Issue by thughes** [ben-gibson/GitLink#103]
Based on https://github.com/ben-gibson/GitLink/issues/61, it sounds like "Open in Custom" will open a pemalink unless the reference doesn't exist on the remote, in which case it will fall back to the branch.

When working with Gerrit, changes for reviews are not in standard branch locations (`refs/heads`), but in the magic `refs/changes` (https://gerrit-review.googlesource.com/Documentation/intro-user.html#upload-change), which is what I think may be causing it to not open a permalink when I have a review change checked out.

I'd be fine if there was an option to always open to the commit hash, even if it doesn't exist on the server. I also see the slow behavior described in https://github.com/ben-gibson/GitLink/issues/97, so it sounds like supporting that would solve my problem too.

**Comment by ben-gibson** [comment]
Support for feature #97 has been released.
