### ISSUE TITLE
Changed pattern for lines highlight in URL for Gitlab 12.2+

### ISSUE THREAD

**Issue by l0co** [ben-gibson/GitLink#105]
In GitLink 3.3.1.

I have a GitLab 12.2.4 instance, and GitLink generates following links to the source files with lines highlighted:

```
// multi-line link
https://gitlab.server.com/.../build.gradle#L69-L74

// single-line link
https://gitlab.server.com/.../build.gradle#L69-L69
```

However, for this version of GitLab it doesn't work and a proper links should look like this:

```
// multi-line link
https://gitlab.server.com/.../build.gradle#L69-74

// single-line link
https://gitlab.server.com/.../build.gradle#L69
```

**Comment by ben-gibson** [comment]
Hmm, that's how it should be building the URL. Are you sure you have `GitLab` selected as the host?

**Comment by l0co** [comment]
Somehow it was reset to GitHub at some point. So, it works well now. Thanks!
