### ISSUE TITLE
Redundant SSH prefix in GitLab repo URL

### ISSUE THREAD

**Issue by Tensho** [ben-gibson/GitLink#106]
Hi

When I click "Open in GitLab" for GitLab repo with SSH remote origin this plugin doesn't remove `ssh` prefix from the URL.

```
https://ssh.gitlab.acme.in:alpha/beta/blob/...
```
```
$ git remote -v
origin	git@ssh.gitlab.acme.in:alpha/beta (fetch)
origin	git@ssh.gitlab.acme.in:alpha/beta (push)
```

#### Expected Behaviour

Link without `ssh`:

```
https://gitlab.acme.in:alpha/beta/blob/...
```

#### GoLand Settings

- **Hosts:** GitLab (BTW, I guess the label should be "Host")
- **Force HTTPS:** enabled

#### Desktop

- **GitLink:** 3.3.1 / 3.3.2
- **IDE:** JetBrains GoLand 2019.2.2
- **OS:** macOS Mojave 10.14.6 / macOS Catalina 10.15.2
- **Browser:** Chrome 77.0.3865.90 (Official Build) (64-bit) / Chrome 79.0.3945.79 (Official Build) (64-bit)

**Comment by ben-gibson** [comment]
Do you need the SSH subdomain? I.e. could you set origin to `git@gitlab.acme.in:alpha/beta`? That's the URL format gitlab uses normally

**Comment by Tensho** [comment]
I have an on-premise GitLab deployment and work with it within SSH.

**Comment by simonberger** [comment]
This is a very edge case request. If the leading ssh prefix/subdomain is not a reserved part of the SSH-address I would not manipulate the URL and risk it fails for someone else.

**Comment by ben-gibson** [comment]
Yeah, I agree. Perhaps using the custom host type would be the best solution for this.

**Comment by Tensho** [comment]
Sorry, not sure I'm clear about the proposed solution. Is it a big deal to allow GitLab url customization in the plugin settings?

**Comment by ben-gibson** [comment]
You can already achieve what your looking for using the custom host type. There's some documentation on the wiki [here](https://github.com/ben-gibson/GitLink/wiki/Custom-Host) that should help you get it configured in the way you want. For example, you probably want something like

```
"https://gitlab.acme.in/alpha/beta/blob/{branch}/{file:path}/{file:name}#L{line:start}-{line:end}",
"https://gitlab.acme.in/alpha/beta/blob/{commit}/{file:path}/{file:name}#L{line:start}-{line:end}",
"https://gitlab.acme.in/alpha/beta/commit/{commit}"
```

**Comment by Tensho** [comment]
@ben-gibson Thank you for the reference 🙇  I've resolved the issue with the host with Custom URL, but still can't compose GitLab URL, because the template language doesn't allow to calculate a hash for the file path:
```
https://gitlab.acme.in/alpha/beta/commit/ce67dd49ba58b07178843a00e4695e8cefc4762e#d0b9a8bb1b80b1be94e20823332547113faeeec7_11_10
```
requires something like this:
```
https://gitlab.acme.in/alpha/beta/commit/{commit}/{file:full_path:sha256}#L{line:start}-L{line:end}
```
Real-world GitLab project URL example:
```
https://gitlab.com/gnachman/iterm2/commit/7bb2cbaaea16f065a274dc448618761a37661f22#c6bf42663839de70b1bf22ca480e3ceeb846e6ab_4411_4414
```
Does it sound like a feature request?

**Comment by Tensho** [comment]
@ben-gibson Any thoughts?

**Comment by ben-gibson** [comment]
You could still generate a link to the file directly at that the given commit for example, on GitLab that would be something like:

`https://gitlab.com/gnachman/iterm2/-/blob/25f43d96421d93c24d3c4f74535d76138f97599e/sources/PTYTextView.m
`
It does look like a nice feature to support though, linking to the file within the commit diff using the file hash anchor. It should be a pretty simple feature to add assuming we have everything we need to generate the hash correctly. You could submit a PR to add the functionality or you could create a feature request (though I'm not sure when I'll have time to look at it).

**Comment by Tensho** [comment]
Thank you, I didn't know about the alternative link (`blob`) 🙇 
How can I switch between "File at Commit", "File at Branch" and "Commit" URLs within UI? I see only "Open in Custom" and it opens "File at Commit" only.

TBH, I have no idea what is the data should be passed to hash function. I guess it's a sacred GitLab knowledge 😅

**Comment by ben-gibson** [comment]
It will depend on where you use select it from for example, if you open the annotation gutter and right click you will get the option to open either the commit or the file at the commit. File at branch is only used when the commit doesn't exist on the remote e.g. it's not be pushed.

**Comment by ben-gibson** [comment]
This is something we could probably add to the plugin description page, a GIF demonstrating the different places it can be used.
