### ISSUE TITLE
Dead link for project on Atlassian's Stash

### ISSUE THREAD

**Issue by Hongbo-Miao** [ben-gibson/GitLink#118]
**Describe the bug**
The plugin looks promising!
My repo is on Atlassian's Stash, right now GitLink goes to wrong URL which show

> Oops, you've found a dead link
> Use the links at the top to get back.

**To Reproduce**
When I right click one line in my code, it goes to
https://stash.company.com/PROJECTNAME/my-repo/blob/44a94b1fbd75506ba3a7dd62a0a717068c395d1b/index.js#L25-L25

**Expected behavior**
The working link for corresponding code line on master is at
https://stash.company.com/projects/PROJECTNAME/repos/my-repo/browse/index.js#25

**Desktop (please complete the following information):**
 - GitLink version 3.3.3

**Comment by ben-gibson** [comment]
Try the host `BitBucket Server`, that should solve the issue.

**Comment by Hongbo-Miao** [comment]
Hi @ben-gibson thank you for help!

I downloaded Bitbucket Server at
https://www.atlassian.com/software/bitbucket/download

After installing, I just started by
![image](https://user-images.githubusercontent.com/3375461/79292208-232cf600-7f03-11ea-9705-9422d4a8f8ff.png)

But still goes to same dead URL. I might not totally understand your suggestion.

**Comment by ben-gibson** [comment]
Sorry, I mean, in the plugin settings from your IDE `Preferences->Other Settings->GitLink` and change the host to `BitBucket Server`

**Comment by Hongbo-Miao** [comment]
Wow, it is working. Thank you soooo much!
