### ISSUE TITLE
invalid gitlab link

### ISSUE THREAD

**Issue by kamarton** [ben-gibson/GitLink#119]
**Describe the bug**
Generated link is wrong if has start and end lines contains in hash mark.

**To Reproduce**
1. Go to a static php method
2. Click on context menu `copy github link`
3. generated url is wrong

**Expected behavior**
- correct: `https://gitlab.example.com/mygroup/myproject/blob/977ac19d4d4f3bb3ed6fce0fa78d658a7925df75/common/helpers/EnvironmentHelper.php#L429-429`
- wrong: `https://gitlab.example.com/mygroup/myproject/blob/977ac19d4d4f3bb3ed6fce0fa78d658a7925df75/common/helpers/EnvironmentHelper.php#L429-L429`

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser -
 - Version -

**Additional context**
- Gitlab runs on its own server (self hosted) `GitLab Community Edition 12.9.4`

**Comment by ben-gibson** [comment]
Are you sure you have `GitLab` selected as the host in the plugin preferences? It can't auto detect the host so it will default to `GitHub` which uses the format you're seeing.

**Comment by kamarton** [comment]
> Are you sure you have `GitLab` selected as the host in the plugin preferences? It can't auto detect the host so it will default to `GitHub` which uses the format you're seeing.

I haven't done a setup (plugin preferences), but I can't find the option for that at currently (`PhpStorm`).

**Comment by ben-gibson** [comment]
`PhpStorm -> Preferences->Other Settings -> GitLink`

**Comment by kamarton** [comment]
thanks!
