### ISSUE TITLE
Opening code in GitLab does not highlight the specified line

### ISSUE THREAD

**Issue by caalberts** [ben-gibson/GitLink#120]
**Describe the bug**

Opening a line in GitLab uses the URL in the format of `https://gitlab.com/{path}/blob/{sha}/file.extension#L1-L1`. This does not highlight the lines as expected, as the format should be `https://gitlab.com/{path}/blob/{sha}/file.extension#L1-1`

**To Reproduce**
1. With a GitLab repository, right click on a line and `Open in Git...`
2. Browser opens with the URL `https://gitlab.com/{path}/blob/{sha}/file.extension#L1-L1`
3. The line number 1 is not highlighted

**Expected behavior**

Line number 1 should be highlighted.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by ben-gibson** [comment]
Have you configured `GitLab` as the host in the plugin settings? `Preferences -> Other Settings -> Git Link`

**Comment by caalberts** [comment]
Thanks! Turns out it was still GitHub. I had an impression that it was already configured.
