### ISSUE TITLE
Option to add context to GitLab path

### ISSUE THREAD

**Issue by sbglasius** [ben-gibson/GitLink#123]
When I try to open GitLab from the IDE, I do not get the context path, thus getting an error.

When I open my repo i go to:
https://my.server/group/repo

I would like to be able to insert a context path in my url

https://my.server/git/group/repo

My remote is
git@my.server:group/repo.git

**Comment by ben-gibson** [comment]
If the `GitLab` host type doesn't work for you out of the box you should be able to use the custom host type to get what you need. There's some documentation on how to use it [here](https://github.com/ben-gibson/GitLink/wiki/Custom-Host). To configure it, just go to the plugin settings `Preferences->Other Settings->Git Link`
