### ISSUE TITLE
Copy directory path shouldn't have line number

### ISSUE THREAD

**Issue by lingsamuel** [ben-gibson/GitLink#133]
**Describe the bug**
Copy directory path will generate line number, such as `https://github.com/<org>/<repo>/blob/<hash>/path/to/dir#L1-L1`.

**To Reproduce**
1. Select any directory
2. Copy
3. Paste
4. The link has current file line number or #L0-L0 if there is no opened file

**Expected behavior**
Generate `https://github.com/<org>/<repo>/blob/<hash>/path/to/dir` only

**Comment by ben-gibson** [comment]
Thanks, that doesn't look right. I'll look to get that fixed this week.
