### ISSUE TITLE
Custom Host with {branch} uses remote branch instead of local branch name

### ISSUE THREAD

**Issue by AlexTrotsenko** [ben-gibson/GitLink#134]
**Describe the bug**
Whenever I use `{branch}` it renders "remote" branch e.g. `origin/master` instead of `master`

**To Reproduce**
1. Go to 'GitLink setting -> Host -> Custom ->File on branch'
2. Click on 'add any template with {branch} e.g. {remote:url}/browse/{file:path}/{file:name}?at=refs/heads/{branch}'
3. Close settings and in for the any file In the editor click 'Open in Custom'

**Expected behavior**
Browser is open with url like  ....MyLocalClass?at=refs/heads/master

**Actual behavior**
Browser is open with url like  ....MyLocalClass?at=refs/heads/**origin**/master

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome 89.0
 - Version: GitLink 3.3.3 / Android Studio 4.1.2

**Comment by ben-gibson** [comment]
Hmm I can't seem to reproduce that, are you sure that you're not on the remote branch when you're running that? Also, is the default branch configured in the GitLink settings definatly `master` and not `origin/master`?

**Comment by AlexTrotsenko** [comment]
@ben-gibson  thanks for your reply. I have checked and I have `master` in the settings. 
The branch, which I did checkout is **not** `origin/master` either.

Just in case, following is the screenshot of the settings :
<img width="1109" alt="gitlink_settings" src="https://user-images.githubusercontent.com/4673265/116226586-727f4680-a753-11eb-9438-2fb75aee85aa.png">
