### ISSUE TITLE
PhpStorm can you force https over http link of GitHub on the Copy GitHub link

### ISSUE THREAD

**Issue by mbaric** [ben-gibson/GitLink#137]
Hi @ben-gibson,

First of all from one developer to the other, thank you very much for this plugin it's a life saver.

I would like this simple feature for one simple reason, when I as team lead review the code from developers I often use _blob_ shortcut from GitHub repository to show them where they can look for example.

![image](https://user-images.githubusercontent.com/2319358/115254799-fcb12480-a12d-11eb-80c4-abab1d1e70b1.png)

![image](https://user-images.githubusercontent.com/2319358/115255559-adb7bf00-a12e-11eb-9944-157cc53816d7.png)

So when I did a copy paste on the file in GitHub (3 dots aside) and copied the lines as permalink I realized the only difference between native GitHub in browser blob link and yours is in http/https link.

![image](https://user-images.githubusercontent.com/2319358/115254011-3d5c6e00-a12d-11eb-8781-2cd9fc0e7ca0.png)

With GitHub I got: https://github.com/xyz/xyz-api/blob/1eba0ec73dc363380d889a08ee1dd66c34f84a6c/tests/Http/Controllers/V3/UserControllerTest.php#L22-L53

With Your Plugin inside PhpStorm by clicking on _Copy GitHub link_ I get: http://github.com/xyz/xyz-api/blob/1eba0ec73dc363380d889a08ee1dd66c34f84a6c/tests/Http/Controllers/V3/UserControllerTest.php#L22-L53

Would you be so kind to check this out.

FYI my origin is set with ssh
```
mbaric@i7 /var/www/html/api (feature/TECH-3333) $ git remote -v
origin  git@github.com:xyz/api.git (fetch)
origin  git@github.com:xyz/api.git (push)
```
Perhaps there is some other tip and trick to make this happen. Looking forward to your response. Cheers.

**Comment by ben-gibson** [comment]
You can force HTTPs from the plugin settings in Preferences -> Other Settings -> GitLink. It would be better if that was the default behaviour though, with the option to opt-out of HTTPS if required.

**Comment by mbaric** [comment]
Hi @ben-gibson . I see it inside the Windows machine, will check it also inside the Linux machine, but it's working, thank you for your help.

And yes I agree with you that it should by default FORCE Https, but it's working that is the most important. Cheers thanks for your help.
