### ISSUE TITLE
Gitlab line anchors don't work because of invalid range format

### ISSUE THREAD

**Issue by hexarobi** [ben-gibson/GitLink#138]
**Describe the bug**
When right-clicking and choosing "Copy GitHub link" the link that is copied will include a hashtag anchor link to a range (Ex: `#L30-L35`. This anchor works fine for GitHub but for GitLab the closing line number for the range should NOT include the `L` character. The proper anchor for GitLab would be `#L30-35`. Note even a single line link is treated as a range so this effects those as well.

**To Reproduce**
1. Go to any file hosted on a GitLab repository, right-click and choose "Copy GitHub link"
2. Paste this link into a browser and notice the line anchor does NOT work as intended to highlight and scroll your viewport to the specific lines.
3. Modify URL to remove the 2nd `L` character in the range and re-request the page.
4. Note the anchor DOES work as intended.

**Expected behavior**
Anchors to line ranges should be respected within GitLab as well as GitHub

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 90

**Additional context**
Example link with broken anchor: https://gitlab.com/pgjones/quart/-/blob/master/setup.py#L50-L50
Example link with working anchor: https://gitlab.com/pgjones/quart/-/blob/master/setup.py#L50-50

**Comment by gdagitrep** [comment]
@hexarobi Go to Editor's Preferences -> GitLink Settings -> Host & make it GitLab (default is gitHub, so it follows Lx-Ly pattern)

**Comment by hexarobi** [comment]
Thanks! I didn't even know that settings panel existed, that totally worked! 😄 🙏
