### ISSUE TITLE
How to add custom url for Azure

### ISSUE THREAD

**Issue by anujism** [ben-gibson/GitLink#139]
**Is your feature request related to a problem? Please describe.**
I am using Azure devops and it would be great if this can support it or have an example to do it using custom url. Thanks.

**Describe the solution you'd like**
Add custom url documentation for azure devops.

**Describe alternatives you've considered**
Add it as part of the plugin.

**Additional context**
This is how the git url for repo looks like: 

https://dev.azure.com/OrgName/SubOrgName/_git/RepoName?path=%2Ffolder_name%2Ffilename.py&version=GBmaster&line=10&lineEnd=11&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by gavvvr** [comment]
Just completed setup and it seems to work (at least for _file on commit_, I do not know how to check the rest)


- File at commit:
```
{remote:url}?path={file:path}/{file:name}&version=GC{commit}&line={line:start}&lineEnd={line:end}&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents
```

- File on branch:
```
{remote:url}?path={file:path}/{file:name}&version=GB{branch}&line={line:start}&lineEnd={line:end}&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents
```

- Commit:
```
{remote:url}commit/{commit}
```

**Comment by gadelkareem** [comment]
Is this still working? It does not work for me. It ends up with a URL like this: https://ssh.dev.azure.com/v3/org/Team/repo?path=src/README.md&version=KJGHsldkfh8765sfkjshdfkhfwieyKGJ&line=15&lineEnd=15&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

I added `.idea/GitLinkConfig.xml` but didn't work.

**Comment by Alina1999mikh** [comment]
When I use
{remote:url}?path={file:path}{file:name}&version=GC{commit}&line={line:start}&lineEnd={line:end}&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

I can't see which line is selected, because line=lineEnd. How I can fix it?

**Comment by gavvvr** [comment]
@Alina1999mikh as for now Azure links get generated "out of the box" without any additional manual configurations
