### ISSUE TITLE
Copy link doesn't work when a directory contains certain characters

### ISSUE THREAD

**Issue by troy-lamerton** [ben-gibson/GitLink#140]
**Describe the bug**

**To Reproduce**

1. Open file: Assets/#/Sources/Code.cs
2. Right-click -> Copy GitLab Link
3. Link copied is http://gitlab.myexample.com/Big/project/blob/feature/one/Assets/#/Sources/Code.cs
4. Try to open this in browser and gitlab redirects to repository home page

**Expected behavior**

The copied GitLab link opens the code page in browser, even when a directory name contains the hash character (`#`).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest
 - Version: GitLink 1.0.4

**Additional context**

The `#` character has special meaning in urls, so it should be percent encoded when part of the path.

This link works:
http://gitlab.myexample.com/Big/project/blob/feature/one/Assets/%23/Sources/Code.cs
(the `#` character has been replaced with `%23`)

**Comment by troy-lamerton** [comment]
This is still an issue in GitLink v3.3.6

Can you point me to the code which constructs the url? I'd be happy to submit a pull request

**Comment by ben-gibson** [comment]
I'm in the progress of building version 4.0.0 which is a rewrite of the plugin in kotlin. I'll make sure to include this.

**Comment by troy-lamerton** [comment]
This is also an issue in GitLink 4.0.1.

- Expected copied link: https://gitlab.example.com/Org/gamerepo/blob/master/Assets/%23/Sources/Code.cs#L15-15
- Actual copied link: https://gitlab.example.com/Org/gamerepo/blob/master/Assets#/Sources/Code.cs%23L15-15

**Comment by ben-gibson** [comment]
Oops, fixing this now!

**Comment by ben-gibson** [comment]
https://github.com/ben-gibson/GitLink/pull/175

**Comment by ben-gibson** [comment]
This should be fixed in `4.0.2` 🤞 . Can you confirm?

**Comment by troy-lamerton** [comment]
It's fixed in 4.0.2 👍
