### ISSUE TITLE
GitLab doesn't allow "empty" line range, e.g #L50-50

### ISSUE THREAD

**Issue by kungfutse** [ben-gibson/GitLink#145]
**Describe the bug**
When opening or copying a link to single line of code for a GitLab (self-)hosted project, the appended anchor does not work, as GitLab no longer supports empty range.

**To Reproduce**
1. Copy link to a single line of code
2. Paste it onto browser address bar and press enter
3. Browser doesn't scroll to the correct position

**Expected behavior**
The browser will scroll to a correct position in the code

**Additional context**
#L50-50 -> Doesn't work
#L50 -> Works
#L50-51 -> Works

**Comment by jacobshilitz** [comment]
I just tested this and it seems to auto scroll on my self hosted gitLab v13.12.8 with `orders.php#L541-541` in the url 

I would suggest you to try in another browser, or in incognito, it might be you have a extension that block the scroll

**Comment by mfriedenhagen** [comment]
It guess this is fixed: https://about.gitlab.com/releases/2021/07/22/gitlab-14-1-released/#github-formatted-anchor-links-highlight-correctly
