### ISSUE TITLE
Add support for https://source.chromium.org/

### ISSUE THREAD

**Issue by thughes** [ben-gibson/GitLink#153]
Would it be possible to add support for https://source.chromium.org? The "custom" host features seems to provide 90% of the functionality, but it seems to assume that the source is hosted on the same place as the viewing tool. In this case, the source repository is  https://chromium.googlesource.com, but the viewer is https://source.chromium.org.

**Comment by thughes** [comment]
I tried with `4.0.5` and it's *almost* working.

Here's the problem I'm seeing:

BaseURL is set to `https://chromium.googlesource.com`.

I have `File at branch template` set to:

```
https://source.chromium.org/chromiumos/chromiumos/codesearch/+/refs/heads/{branch}:src/{remote:url:path:1}/{file:path}/{file:name};l={line:start}-{line:end}
```

This works for the following repo `https://chromium.googlesource.com/chromiumos/platform2`, but not for repos with longer paths such as `https://chromium.googlesource.com/chromiumos/platform/ec`.

Instead of being able to reference a single part of the path with `{remote:url:path:n}`, it looks like I need to be able to specify a range. Something like: `{remote:url:path:[1:]}`.

**Comment by ben-gibson** [comment]
Yeah, I think we can add `chromium` as a support host. I'll take a look later this evening to see what it would involve. I'm away next week, but should be able to add it the week after.

**Comment by ben-gibson** [comment]
I've struggled with the Chromium [viewer](https://source.chromium.org/), it seems to have a different URL structure depending on which project you're viewing. I've created a PR with a quick prototype as best I can here https://github.com/ben-gibson/GitLink/pull/187. 

Could you give it a try and let me know if it's close to what you need? You can get the plugin artifact here https://github.com/ben-gibson/GitLink/actions/runs/2213799186

**Comment by ben-gibson** [comment]
@thughes any luck trying this out?

**Comment by ben-gibson** [comment]
I've added this with a `Experimental` label in `4.0.7`.
