### ISSUE TITLE
[Feature Request] Display link when user right clicks line number

### ISSUE THREAD

**Issue by JordanRifaey** [ben-gibson/GitLink#159]
Thank you for making this plugin, it is very helpful and I wish I had downloaded it sooner.

Please consider adding the link to open in github in the panel that is displayed when you right click next to the line number. I think this is more intuitive than having it be under "View" in the top menu bar. But maybe its currently not there because plugins dont have the ability to add items to that panel? This would be super helpful to me and i'm sure a lot of other people. thank you.

![image](https://user-images.githubusercontent.com/29124844/146062675-0042ce9e-da39-4635-a0b4-c11652047139.png)

**Comment by ben-gibson** [comment]
This may be implemented in the upcoming version 4.0.0, I'll close this issue for now so we can re-review after the new version is released.
