### ISSUE TITLE
"GitLink - Opening File" task takes over a minute to complete

### ISSUE THREAD

**Issue by alihaghani** [ben-gibson/GitLink#160]
**Describe the bug**
Used with GitHub Enterprise, copying a link to the current file takes over a minute to complete.

**To Reproduce**
1. Go to 'View'
2. Click on 'Copy GitHub Link'
3. Wait about a minute for the "GitLink - Opening File" background task to complete to paste the URL elsewhere

**Expected behavior**
The task should take a few seconds at most.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1
 - IDE: RubyMine
 - GitLink version: 3.3.6

**Comment by jzoch-stripe** [comment]
I have the same behavior

**Comment by ben-gibson** [comment]
What happens if you uncheck the `Check commit exists on remote` option in the plugin settings `Preferences -> GitLink`. Does it improve the performance?

**Comment by jzoch-stripe** [comment]
@ben-gibson i found unchecking that made performance incredibly fast. The only downside is im constantly giving bad links to folks until I push my branch

**Comment by alihaghani** [comment]
> What happens if you uncheck the `Check commit exists on remote` option in the plugin settings `Preferences -> GitLink`. Does it improve the performance?

Yep, that makes the task complete almost instantly. I'm ok with that tradeoff, thanks!
