### ISSUE TITLE
Add capability for different subdomain than the remote url

### ISSUE THREAD

**Issue by IanBurwell** [ben-gibson/GitLink#161]
I am using a bitbucket cloud server with remote host url `sshgit.mysite.com` but want a link generated to `git.mysite.com` as that is where the web interface is. Changing `{remote:url}/src/HEAD/{file:path}/{file:name}?at={branch}#lines-{line:start}:{line:end}` to `git.mysite.com/src/HEAD/{file:path}/{file:name}?at={branch}#lines-{line:start}:{line:end}`. Sadly results in an error.

```
Cannot create url (Could not create a valid URL using the template (ssh.mysite.com/projects/{remote:url:path:0}/repos/{remote:url:path:1}/browse/{file:path}/{file:name}?at=refs/heads/{branch}#{line:start}-{line:end}))
```

**Comment by ben-gibson** [comment]
Have you tried setting the protocol i.e. `git.mysite.com/src/HEAD/{file:path}/{file:name}?at={branch}#lines-{line:start}:{line:end}`? Reopen if you're still having issues and I can take a look.

**Comment by IanBurwell** [comment]
Using the suggested string i still run into the invalid URL error.
<img width="942" alt="Screen Shot 2022-03-10 at 9 20 28 AM" src="https://user-images.githubusercontent.com/15115967/157681136-3d5334fb-77f5-44b0-8521-59e607cb9593.png">

`Cannot create url (Could not create a valid URL using the template (git.mysite.com/src/HEAD/{file:path}/{file:name}?at={branch}#lines-{line:start}:{line:end}))`

**Comment by ben-gibson** [comment]
Sorry, I was supposed to include the protocol in my example, does this work `https://git.mysite.com/src/HEAD/{file:path}/{file:name}?at={branch}#lines-{line:start}:{line:end}`

**Comment by IanBurwell** [comment]
Ah yes, it works like a charm now. Thanks! And yeah, a custom URL host as an optional field would be handy.
