### ISSUE TITLE
Add a global configuration with project specific overrides

### ISSUE THREAD

**Issue by ericeubank-powerschool** [ben-gibson/GitLink#162]
**Is your feature request related to a problem? Please describe.**
Currently you have to configure GitLink per project. If you work at a company with multiple projects, chances are they are all by the same source control provider. It would be great if you only had to configure this once for most projects, and have an override for one-offs which may be hosted differently.

**Describe the solution you'd like**
In the GitLink configuration dialog, have a `Global` or `Default` configuration area. In the current `Project Settings` area, have a check box to enable overrides for the current project.

**Describe alternatives you've considered**
A more advanced option might be to allow for preset configurations to be defined and one marked as the default.

**Comment by ben-gibson** [comment]
Something like this will be in the upcoming `4.0.0` version. Potentially using the `Default Project Settings`
