### ISSUE TITLE
"Open in GitHub" (and "Copy GitHub link") very slow

### ISSUE THREAD

**Issue by nurous** [ben-gibson/GitLink#165]
**Describe the bug**
"Open in GitHub" (and "Copy GitHub link") are very slow on new mac

**To Reproduce**
1. Go to any file in a github project
2. Right Click and select 'Open in GitHub'
3. Background task runs for minutes before opening the page in the browser

**Expected behavior**
Background task should take only a few seconds at most

**Desktop (please complete the following information):**
 - Mac OS v 12.2.1 (Macbook Pro M1 Chip)
 - IntelliJ IDEA CE v 2021.3.2.IC-213.6777.52
 - GitLink v 3.3.6

**Comment by ben-gibson** [comment]
Is the repository you're using this with big? Does it improve if you uncheck `check commit on remote` option from the plugin settings `Preferences -> Other Tools -> GitLink`?

**Comment by nurous** [comment]
Yes, it was a large repo that I was doing it with.
Unchecking `check commit on remote` did make it fast as expected, perhaps I had that already disabled on my previous machine.
