### ISSUE TITLE
Feature request: Create per-line link from IDEA's sidebar with line numbers

### ISSUE THREAD

**Issue by ujay68** [ben-gibson/GitLink#166]
If possible for a plugin, provide an _Open in (your selected host)_ action not only in the _View_ menu, but also in the sidebar of a source file, where IntelliJ IDEA shows the line numbers of that file, and make that action create a line-specific link. In GitLab, that's just an additional HTML anchor like `#L???`, where `???` is the line number.

**Comment by ben-gibson** [comment]
Thanks for the request, that should now be available in the latest version `4.0.1`

**Comment by ujay68** [comment]
Great. Thank you so much.

**Comment by ujay68** [comment]
Tried it out with v4.0.3 and IDEA 2022.1, but it didn't work for me. All links copies from the sidebar contain an anchor like `#123-123` with a double line number.

**Comment by ben-gibson** [comment]
That still has the same result as having an anchor like `#123` though doesn't' it? i.e. it still inks to the file in `Gitlab` and selects the expected line `123`

**Comment by ujay68** [comment]
Tested a little more. Seems to be a Safari and/or GitLab issues. Opening anchored links works in macOS Chrome, both with `#L123` and `#L123-123`, and Chrome scrolls to the targeted line in both variants. Safari highlights the line in both variants, but doesn't scroll there with the double-line-number variant, only with the `#L123` one.

Safari v15.4, GitLab v14.9.3-ee
