### ISSUE TITLE
Wrong line numbers if there are collapsed code sections

### ISSUE THREAD

**Issue by frozenice** [ben-gibson/GitLink#179]
If there are collapsed sections in the editor (doesn't matter if e. g. imports or a method), the line numbers appended to the link anchor are off. By collapsed I mean the IntelliJ editor feature where you can click the little plus and minus buttons next to the line numbers - some stuff like imports might also be automatically collapsed. Selecting multiple lines has the same problem.

An example: There are 11 `import` lines, which are collapsed, so only 1 is shown (i. e. 10 are hidden). I right-click in line 15 and select the GitLink action "Open in ...". The link anchor is `#5-5`. With all `import` lines visible (i. e. uncollapsed), the link anchor is `#15-15`.

Awesome plugin btw! :)

**Comment by ben-gibson** [comment]
Thanks for reporting! This should be fixed in `4.0.5`. Can anyone confirm?

**Comment by thughes** [comment]
Working now with `4.0.5`. Thanks for the quick response!

**Comment by frozenice** [comment]
Yes, `4.0.5` works flawlessly, tyvm!
