### ISSUE TITLE
Link number for Github link is off if using import folding

### ISSUE THREAD

**Issue by jtorson-fs** [ben-gibson/GitLink#186]
I'm using Goland and this appear like a recent bug. When I try to generate a link the past few days, the line number is always off. I figured out it's because of the import folding/hiding feature. If I expand the imports on a tsx (React) file, then it works like it should. I recently updated and I think I updated about a month ago and this worked just fine then.

**Comment by ben-gibson** [comment]
This should be fixed already in `4.0.5` (#179 ). Could you check the version your using and report back if it's still an issue in `4.0.5`.

**Comment by jtorson-fs** [comment]
> This should be fixed already in `4.0.5` (#179 ). Could you check the version your using and report back if it's still an issue in `4.0.5`.

This is working now in 4.0.5! Sorry I checked for updates before opening this but didn't see anything then.

Thanks!
