### ISSUE TITLE
No option to copy permalink in new version?

### ISSUE THREAD

**Issue by nazarewk** [ben-gibson/GitLink#190]
In previous versions i've noticed copying GitHub link gave me a link to the commit.
After updating the plugin it copies the branch link, it would be useful to have (separate?) option to copy a permalink directly from IDE.

**Comment by ben-gibson** [comment]
Hmm, it should be using the commit 🤔. The only reason it would use the branch instead is

* The commit hasn't been pushed to the remote
* The `Check commit on remote` option in the plugin settings has been unchecked.

Can you confirm neither of those are the case?

**Comment by nazarewk** [comment]
I have unchecked the check commit on remote because it takes a few seconds and breaks seamless usage of the plugin.

**Comment by ben-gibson** [comment]
The only problem with using the commit without that options enabled is, there's no way to know if it's been pushed to the remote, so the generated URL could lead to a 404. I guess that could always been an option configured from the plugin settings though. For example, when unchecking `Check commit on remote`. A radio button is shown to choose if the current commit or current branch is preferred

**Comment by nazarewk** [comment]
It would be great to have an option to prefer copying branches or commits separate from the `Check commit on remote`

**Comment by ben-gibson** [comment]
I think this is mostly solved now based on https://github.com/ben-gibson/GitLink/issues/202
