### ISSUE TITLE
Feature: Custom Host improvements + Detect remote based on domain

### ISSUE THREAD

**Issue by TheBestPessimist** [ben-gibson/GitLink#191]
My remote is like this: `https://gitlab.common.cloud.tra.lala/tra/la/la-pltf/tra-pltf/lala-at/capacity/`. It can be easily seen that it's a gitlab remote.

I would like when adding a custom host, to have a "copy from predefined template" dropdown which takes all settings from one of the default remotes from GitLink (Gitlab, Github, Gitea, etc.). I don't wanna have to add all of the "template fields" manually when they don't change:

![image](https://user-images.githubusercontent.com/4482210/165053018-245842b9-f990-4147-8d35-9fc4c0e23a4b.png)

It would be even nicer if maybe based on the domain `gitlab.common.cloud.tra.lala`, Gitlink could detect that this is a gitlab remote automatically, without me needing to create a custom host. In this case, in the notification I would get a message `We've detected your remote as "Gitlab". If this is not correct, please select your remote` and the same button as we get now.

**Comment by TheBestPessimist** [comment]
One thing which works right now is to not set a Custom Host, but instead simply select Gitlab as host. The problem is i need to do this for every new repository i clone, which is less than ideal.

**Comment by ben-gibson** [comment]
Yeah, having something in the plugin settings to register additional domains for a host would be nice for this. I'll take a look next week

**Comment by ben-gibson** [comment]
This should be possible in `4.1.0` under the new `Auto-detect` page in the plugin settings.

**Comment by TheBestPessimist** [comment]
This works with a minor caveat: it does not work right after cloning a project - the Intellij project window needs to be closed and reopened.

Step by step repro:
1. have intellij open with an existing project (`p1`) and have already setup the custom hosts.: `custom.gitlab` is my host
2. using <kbd>File</kbd>-> <kbd>New</kbd>-><kbd>Project from Version Control</kbd>, clone the repository `https://custom.gitlab/myrepo`
3. a new intellij window opens and intellij starts importing the project and dependencies etc. `README` is open by default
4. ❌ if i right click on the readme, there's no gitlink entries
5. close the window for project `myrepo`, leave the other one open (`p1`)
6. open the project `myrepo`
7. ✅ if i right click on readme (file is still open since last time), there are gitlink entries

**Comment by TheBestPessimist** [comment]
Now it's even worse: step 6. is also broken: the host is not autoselected even after a project restart.

So with v4.1.4 i need to manually set the host, even though i have the domain registry set up.


```
IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
Build #IU-222.2270.31, built on May 18, 2022
Licensed to IntelliJ IDEA EAP user: Cristian Pasat
Expiration date: June 17, 2022
Runtime version: 17.0.3+7-b423.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 6096M
Cores: 12
Registry:
    debugger.click.disable.breakpoints=true
    documentation.show.toolbar=true
    debugger.valueTooltipAutoShowOnSelection=true

Non-Bundled Plugins:
    some.awesome (1.14)
    org.nik.presentation-assistant (1.0.9)
    lermitage.intellij.extra.icons (2022.1.3)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    org.asciidoctor.intellij.asciidoc (0.37.17)
    com.intellij.plugin.adernov.powershell (2.0.10)
    uk.co.ben-gibson.remote.repository.mapper (4.1.4)
    com.intellij.kubernetes (222.2270.31)
    BrowseWordAtCaret (3.0.5)
    izhangzhihao.rainbow.brackets (6.23)
    AceJump (3.8.7)

Kotlin: 222-1.7.20-dev-796-IJ2270.31
```

**Comment by ben-gibson** [comment]
Weird, I couldn't reproduce this on my development machine, but I could on different machine. I've reverted a change that I suspected to be the most likely culprit which seems to have resolved the problem on the secondary machine i was testing with. Can you confirm what behaviour you're seeing now?

**Comment by TheBestPessimist** [comment]
Tested again, the behaviour is smilar to my comment https://github.com/ben-gibson/GitLink/issues/191#issuecomment-1131227704. 

i will copy paste it here for freshness:



Step by step repro:
1. have intellij open with an existing project (`p1`) and have already setup the custom hosts.: `custom.gitlab` is my host
2. using <kbd>File</kbd>-> <kbd>New</kbd>-><kbd>Project from Version Control</kbd>, clone the repository `https://custom.gitlab/myrepo`
3. a new intellij window opens and intellij starts importing the project and dependencies etc. `README` is open by default
4. ❌ if i right click on the readme, there's no gitlink entries
5. close the window for project `myrepo`, leave the other one open (`p1`)
6. open the project `myrepo`
7. ✅ if i right click on readme (file is still open since last time), there are gitlink entries
