### ISSUE TITLE
Do not call git functions when the "Check commit on remote" is turned off

### ISSUE THREAD

**Issue by andras-tim** [ben-gibson/GitLink#201]
I use SSH with pubkey auth, and our repo is enormous, so this checking is sooo long.

Therefore I turned off this checking, but now the PyCharm always asks the ssh user's password (3 times per action)... which is not exist.

I loved the original functionality when this URL creation was a dumb concatenation of the necessary parameters. That was superfast and I expected this functionality when I turn off the mentioned checkbox.

May I ask to recover this functionality when I turns off the **Check commit on remote** option?

**Comment by ben-gibson** [comment]
I've opted to change the existing setting `Check commit on remote` to a more general `Check remote` option that disables all checks on the remote (commit and branch). I think that aligns with the desired behaviour, which is, on large repositories to avoid the performance cost of a remote check. #251

**Comment by ben-gibson** [comment]
This has been released in 4.2.2
