### ISSUE TITLE
Refactor "Domain registry" to a two-column table

### ISSUE THREAD

**Issue by sabi0** [ben-gibson/GitLink#206]
Two-column table provides a better overview of the "registry" than switching the table contents on drop-down selection change.

See for instance File | Settings | Languages & Frameworks | SQL Dialects:
![image](https://user-images.githubusercontent.com/11509875/169494166-2018369e-ca32-4efd-b161-352337f03c35.png)

**Comment by ben-gibson** [comment]
You're right, but it's probably not worth the effort given how infrequently I imagine people will work with these settings.
