### ISSUE TITLE
 Feature reuqest: clear token/username when the origin has it (e.g. https://TheAccessTokenOrUsername:password@github.com/...) #9 

### ISSUE THREAD

**Issue by zlamma** [ben-gibson/GitLink#208]
The username is often added to the origin when a particular developer works with multiple organizations and has multiple accounts with the repository website. There's no reason this needs to be shared, as the link without the username identifies the same resource.

Another reason this better not be exposed is that this part of the URL can actually contain a Personal Access Token (e.g. GitHub [has this feature](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line)).

**Comment by ben-gibson** [comment]
This should now be resolved in `v4.1.4`.
