### ISSUE TITLE
When Idea is re-importing/re-indexing a project, gitlink right click buttons are not clickable

### ISSUE THREAD

**Issue by TheBestPessimist** [ben-gibson/GitLink#214]
Steps to repro

1. have a project opened and setup with gitlink. When right clicking on a file, the 2 options for `copy link` and `open in` are there at the bottom.
2. (this is the fastest way i can repro it reliably) choose option <kbd>File</kbd>-><kbd>Invalidate caches</kbd>
3. untick any options in the modal (to do as little damage as possible), press <kbd>Invalidate and Restart</kbd>
4. Intellij restarts
5. ❌ While intellij is re-importing the (gradle) project, i can see the 2 options however they are unclickable
6. after intellij finishes the import everything is working as expected

IMO, GitLink should not be affected by indexing status.

example for 5.:
![image](https://user-images.githubusercontent.com/4482210/169955031-25c4d813-8436-4fb7-a3ae-d0904e8c818e.png)

One thing to note here, if at step 2 i go to gradle toolwindow and press the refresh button, GitLink works as expected. This is the reason why i suggested using <kbd>Invalidate caches</kbd>.
I have seen this issue happen during _other_ intellij re-indexing, but i cannot reliably reproduce them.

**Comment by ben-gibson** [comment]
The menu actions should no longer be disabled when indexing in v4.1.7 🤞

**Comment by TheBestPessimist** [comment]
🎉 Confirm it's fixed.

Thanks, Ben!
