### ISSUE TITLE
Wrong support for port number in git URL

### ISSUE THREAD

**Issue by schi2m** [ben-gibson/GitLink#218]
Unfortunately plugin doesn't work properly if base repository URL is in following format "git-host-name:8082". In this case port is being removed and plugin creates wrong URL.

**Comment by ben-gibson** [comment]
Can you share the result of `git-remove -v` on your repository along with an example of the working HTTP URL you expect it produce?

**Comment by schi2m** [comment]
What `git-remove -v` does? 
I'm working on windows using git bash and I don't have aforementioned command. 

But answering on your question about GIT HTTP URL we're using in our company. This is the one I keep in mind when I posted this issue.

`http://ocjenkinsc2-ref01:8082/xmp/xmp.git`

**Comment by ben-gibson** [comment]
`git-remove -v` will show how the remote is configured, including the protocol it's using.

In may be, that we want to provide a new option in the plugin settings, either, to allow a specific port to be specified, or just a check box to determine if the port should be stripped away or not.

I think you can work around the issue either way for now, by replacing `{remote:url}` with `http://ocjenkinsc2-ref01:8082` so your template becomes something like `http://ocjenkinsc2-ref01:8082/{remote:url:path}/{branch}/{file:path}/{file:name}{line-block:start}#L{line:start}-{line:end}{line-block:end}`

**Comment by schi2m** [comment]
Workaround that you've suggested works. Thanks. 

One thing I need to tell more is, that now (I just noticed this) I can't even provide URL the way I did that earlier (several minor versions before). Now I can only provide domain name. Protocol name or port are not allowed and validation doesn't let me update configuration if any of these are provided in **domain** field. 

Obviously, as I moved this configuration into template fields, I simply could remove all that forbidden data from domain field, just to make "Update" button enabled.

**Comment by ben-gibson** [comment]
Yeah, that filed is only used for automatically detecting the host when opening a new project so it doesn't need anything more than just the domain. In your case, if you set the domain to `ocjenkinsc2-ref01.com`, when you open a new project with the same remote, it should automatically select the custom host you just created so you don't need to do it manually.
