### ISSUE TITLE
"Host" setting can be unclear - suggest labelling as "Platform"

### ISSUE THREAD

**Issue by xurizaemon** [ben-gibson/GitLink#219]
In the plugin settings, I was confused at first by the use of "Host" in this UI.

As it referred to a "host", I doubted that it would work with our self-hosted Gitlab instance, since "Host: Gitlab" (I figured) seemed likely to refer to the 'default' host `gitlab.com`.

![image](https://user-images.githubusercontent.com/105608/171755542-e95880f7-19bf-49b1-b175-31777611d315.png)

If the input's label was "Platform" then I would have expected it to work with _any_ host which was a Gitlab platform instance.

I now know this works, so it's no longer a problem for me, but thought the UX feedback might help improve the plugin if you agree :)

**Comment by ben-gibson** [comment]
Yeah, perhaps `URL Format` is another option. You're right, `Host` isn't very clear.

**Comment by xurizaemon** [comment]
Agreed, "URL format" would have made more sense to me.

Thanks!

**Comment by ben-gibson** [comment]
Updated in the latest version
