### ISSUE TITLE
custom domain registry

### ISSUE THREAD

**Issue by alanhg** [ben-gibson/GitLink#224]
![image](https://user-images.githubusercontent.com/9245110/174080832-f7fe3dcd-fd3b-4957-be20-c799cec44b33.png)
I think we can support this so that users can add it even if it's not built-in

**Comment by ben-gibson** [comment]
I'm not to sure what you mean on this one? If you create a new custom host, then it should appear in this drop down, where you can then register the domain. Is that what you're referring too?

**Comment by alanhg** [comment]
I know the problem, when you add a custom host, the registry list will not be visible, you need to click Apply.

Currently does support custom domain registry.
