### ISSUE TITLE
the plugin not support sync?

### ISSUE THREAD

**Issue by alanhg** [ben-gibson/GitLink#225]
IDE supports plugin setting sync.

I change gitlink setting and found sync not work. 

so I want to confirm the plugin support sync?

![image](https://user-images.githubusercontent.com/9245110/175755917-6c8f9712-3ff4-4e50-98a8-2758565fb94f.png)

**Comment by ben-gibson** [comment]
As far as I know, the `IDE Settings Sync` should list all enabled/disabled plugins out of the box. I don't think there's anything special a plugin needs to do in order for it to be supported. It might be worth raising this one with the `IDE Settings Sync` plugin support instead, if it's still not showing.
