### ISSUE TITLE
Azure DevOps Links not working

### ISSUE THREAD

**Issue by StefanLobbenmeier** [ben-gibson/GitLink#235]
I tried making this plugin work with our azure devops project, but it seems to generate the wrong urls:
![image](https://user-images.githubusercontent.com/36509607/188433953-94068736-9988-472b-bbe8-d95e69edbb4a.jpeg)

This is the url it generates:
`https://ssh.dev.azure.com/v3/companyname/companyname.de/companyname-client?version=GBbranchname&path=/README.md&line=1&lineEnd=1&lineStartColumn=1&lineEndColumn=1`

That is the link I get manually when copying from Azure DevOps
`https://dev.azure.com/companyname/companyname.de/_git/companyname-client.git?path=/README.md&version=GBbranchname&line=1&lineEnd=2&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents`

I cloned the project via ssh, so maybe this is not supported?

**Comment by ben-gibson** [comment]
What does your remote configuration show? `$ git remote -v`

**Comment by StefanLobbenmeier** [comment]
```
origin  git@ssh.dev.azure.com:v3/companyname/companyname.de/companyname-client.git (fetch)
origin  git@ssh.dev.azure.com:v3/companyname/companyname.de/companyname-client.git (push)
```

**Comment by ben-gibson** [comment]
Are there self hosted options or custom domain support in Azure? If not, this could be as simple as just assuming `https://dev.azure.com/` as the host.

**Comment by cjoecker** [comment]
I don’t have a self-hosted repo and also have the same difference in the url: an extra `ssh.` and `v3` 
Maybe it creates a different url when the repo is cloned using ssh?

**Comment by ben-gibson** [comment]
Possibly fixed in the latest version 4.2.3 🤞🤞

**Comment by StefanLobbenmeier** [comment]
Thanks I will try tomorrow ❤️

**Comment by StefanLobbenmeier** [comment]
It is almost right, I think it is missing a .git at the end of the url:

https://dev.azure.com/companyname/companyname.de/_git/projectname?httpParams

is being generated, but I manually have to change it to 

https://dev.azure.com/companyname/companyname.de/_git/projectname**.git**?httpParams

Otherwise it says 
> Repository "projectname" not found



![image](https://user-images.githubusercontent.com/36509607/196133573-8c16efa7-9fba-4fe8-984e-a582ac97e7cc.jpeg)

**Comment by ben-gibson** [comment]
Does this work now on `v4.2.4`?

**Comment by StefanLobbenmeier** [comment]
I will give it a shot on Monday :smile: thanks

**Comment by cjoecker** [comment]
I tried it and it works, thanks a lot!!

**Comment by StefanLobbenmeier** [comment]
Sorry did not get the plugin update yesterday, but today I was able to update and I can also confirm the bug to be fixed :) thank you very much ❤️
