### ISSUE TITLE
Azure DevOps commit link incorrect

### ISSUE THREAD

**Issue by Bouke** [ben-gibson/GitLink#247]
The URL generated for a commit in Azure DevOps is wrong. Apparently the full hash must be provided and not the short version.

Expected:
```
https://dev.azure.com/organization/Project/_git/Repository/commit/f3e773cf7a13ce5d9db15ddbf888197a07fd9c54
```

Actual:
```
https://dev.azure.com/organization/Project/_git/Repository/commit/f3e773cf
```

<img width="467" alt="image" src="https://user-images.githubusercontent.com/235882/192768876-3b086868-1899-444f-a2bf-b3157f810772.png">

**Comment by ben-gibson** [comment]
That's strange, it should always use the full commit hash. Are you using the custom platform type?
