### ISSUE TITLE
Azure DevOps line selection not preserved

### ISSUE THREAD

**Issue by Bouke** [ben-gibson/GitLink#248]
The selection I've made in Rider isn't preserved and the generated link always seems to reference a single line. A single line selection isn't obvious in the UI, as it doesn't highlight anything. 

The generated link is something along these lines:
```
https://dev.azure.com/organization/Project/_git/Repository?version=COMMIT&path=PATH&line=475&lineEnd=475&lineStartColumn=1&lineEndColumn=1
```
Produces this:
<img width="135" alt="image" src="https://user-images.githubusercontent.com/235882/193047113-3998655a-7abd-47fd-b47f-6de13b10da5d.png">

Whereas the following link is produced by Azure DevOps when selecting a single line:
```
https://dev.azure.com/organization/Project/_git/Repository?version=COMMIT&path=PATH&line=475&lineEnd=476&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents
```
Produces this:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/235882/193047864-b94ffdd8-7cea-4bdb-8cd3-0cc5fa6ac12b.png">

Multi-line selection is also possible, including column offsets:
```
https://dev.azure.com/organization/Project/_git/Repository?path=PATH&version=COMMIT&line=473&lineEnd=474&lineStartColumn=9&lineEndColumn=39&lineStyle=plain&_a=contents
```
Producing this:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/235882/193048140-b360eb32-1d8d-4433-9f38-e1fcb4ba6956.png">

**Comment by ben-gibson** [comment]
This may be a little better in the latest version 4.2.3
