### ISSUE TITLE
Allow domains without `.` in them

### ISSUE THREAD

**Issue by huyz** [ben-gibson/GitLink#253]
I use SSH aliases in order to support multiple GitHub accounts as described in https://gist.github.com/oanhnn/80a89405ab9023894df7

This means that I have a ton of repos configured with URLs like: `	url = git@github-huyz:ben-gibson/GitLink.git`

But GitLink doesn't allow me to enter `github-huyz` in the list of domains for GitHub because it requires a `.` in the name.
Please allow arbitrary strings for the domains. We know what we're doing :)

**Comment by ben-gibson** [comment]
I think this should now be resolved in the latest version `4.2.5`.
