### ISSUE TITLE
Can't use {remote:url:host} or {remote:url:path} in template

### ISSUE THREAD

**Issue by bernhof** [ben-gibson/GitLink#261]
The following template is considered invalid, but I can't see why:

    {remote:url:host}/git/{remote:url:path}/-/blob/{branch}/{file:path}/{file:name}#L{line:start}-{line:end}

![Screenshot of invalid URL](https://user-images.githubusercontent.com/1303750/201334018-171cdff2-918c-403d-8818-30ac713e836a.png)

I'm trying to inject "/git/" between host and repo path.

The following placeholders are listed in the dialog:

![Placeholders](https://user-images.githubusercontent.com/1303750/201334142-78403df0-f0fd-450a-8edb-dc8687ff34d2.png)

Is this a bug, or am I doing it wrong?

Using GitLink plugin version 4.2.4

**Comment by ben-gibson** [comment]
Sorry, I think the example shown for `remote:url:host` is wrong, it should be `example.com`, not `https://example.com`. I think, if you prepend the protocol, it should work. For example, `https://{remote:url:host}/git/{remote:url:path}/-/blob/{branch}/{file:path}/{file:name}#L{line:start}-{line:end}`

**Comment by ben-gibson** [comment]
I've updated the example in the latest version
