### ISSUE TITLE
Links to GitHub do not contain commit ID

### ISSUE THREAD

**Issue by mrh1997** [ben-gibson/GitLink#291]
In contrary to GitLab links to GitHub do not contain the commit ID. This means when opening the links at a later time they can refer a different line (since somebody added a commit that inserted a line before the refererred line).

Sample for a GitHub Links:
`https://github.com/mrh1997/xyz/blob/main/src/components/Xyz.vue#L65-L65`

Sample for a GitLab link (also created with GitLink), but including a commit ID:
`http://gitlab.com/mrh1997/xyz/-/blob/f0d324062d9a1f22a7aaea381d4fb222408e85db/bal27/formats/bf3file.py#L17-17`

**Comment by ben-gibson** [comment]
Is this still a problem? The only reason I can think of it using the branch instead of the commit in the case of `GitHub` is if it can't find the commit on the GitHub remote.

**Comment by mrh1997** [comment]
Looks like  the problem is solved

**Comment by dawei-nava** [comment]
This looks like a problem now, regression?
