### ISSUE TITLE
Azure Git link lands in 404

### ISSUE THREAD

**Issue by murlakatam** [ben-gibson/GitLink#311]
GitLink 
![image](https://github.com/ben-gibson/GitLink/assets/38276/3de9bb78-1c27-4290-9eb6-cbd174d9baa0)
produces url 
https://dev.azure.com/moeedunz/_git/{project_name}/{repository_name}?version=GCfd89ce0e3d7b985ad86adae9318fe1d59dde2239&path={filePath}&line=12&lineEnd=13&lineStartColumn=1&lineEndColumn=1

which is ending up being a 404

![image](https://github.com/ben-gibson/GitLink/assets/38276/6fda08fe-46f9-4564-9738-4485ba11980f)

While changing the url manually to 

https://dev.azure.com/moeedunz/{project_name}/_git/{repository_name}?version=GCfd89ce0e3d7b985ad86adae9318fe1d59dde2239&path={filePath}&line=12&lineEnd=13&lineStartColumn=1&lineEndColumn=1

makes it working again

_git/{project_name} vs {project_name}/_git

**Comment by ben-gibson** [comment]
What does your `git remote -v` output look like?

**Comment by murlakatam** [comment]
origin  git@ssh.dev.azure.com:v3/moeedunz/{project_name}/{repository_name} (push)

It was working fine recently

**Comment by scmrus** [comment]
Same problem.
 
As I see it makes links like that:
```
https://dev.azure.com/symdistro/_git/{{project}}/{{repo}}?....
```
but it should be like that:
```
https://dev.azure.com/symdistro/{{project}}/_git/{{repo}}?....
```

**Comment by scmrus** [comment]
+1

**Comment by murlakatam** [comment]
@scmrus the workaround is to completely uninstall the plugin and then install [previous version](https://github.com/ben-gibson/GitLink/releases/download/v4.3.4/GitLink-4.3.4.zip) from disk
![image](https://github.com/ben-gibson/GitLink/assets/38276/f721765b-185c-49a5-b54e-79e3dfafbe62)

@ben-gibson since it is working with [previous release](https://github.com/ben-gibson/GitLink/compare/v4.3.4...v4.3.5) I bet this [commit](https://github.com/ben-gibson/GitLink/commit/6631e9ac6eb98963219dbf18003d261d5515ec22) has a bug in it.

**Comment by ben-gibson** [comment]
This should be fixed in the latest version thanks to @murlakatam
