### ISSUE TITLE
Show GitLink options in Git History tab

### ISSUE THREAD

**Issue by DuBistKomisch** [ben-gibson/GitLink#321]
If I right click in a file and select "Git" -> "Show History", it opens a History tab in the Git tool window. This tab shows a big list of commits on the left, and right clicking one of them doesn't show any GitLink options. Instead, I have to select "Show in Git Log" which then highlights the commit in the Log tab, and right clicking there does show the GitLink options. It would be faster if the options were available directly from the History tab instead.

![image](https://github.com/ben-gibson/GitLink/assets/703055/2504ba7f-cf64-41ff-be52-d6f690d6cd27)

**Comment by ben-gibson** [comment]
This has been added in `4.5.0`
