### ISSUE TITLE
About gitlab link 404

### ISSUE THREAD

**Issue by yangyang5214** [ben-gibson/GitLink#328]
> I don't know if it's a gitlab version issue, I made the following changes and it worked in my environment

```
# 404
"{remote:url}/-/{object}/{branch}/{file:path}/{file:name}{line-block:start}#L{line:start}-{line:end}{line-block:end}",
# worked
"{remote:url}/{object}/{branch}/{file:path}/{file:name}{line-block:start}#L{line:start}-{line:end}{line-block:end}",
```

![image](https://github.com/ben-gibson/GitLink/assets/23392325/8583b4d2-bb1a-4338-96a6-f9e5edb19e9c)

**Comment by ben-gibson** [comment]
Both versions worked for me, but given you've got an example where it does not work, I've updated the template in `4.5.0`.
