### ISSUE TITLE
Azure custom domain is not working

### ISSUE THREAD

**Issue by mutoe** [ben-gibson/GitLink#329]
![image](https://github.com/user-attachments/assets/f043780f-a585-4314-a622-102040f2415b)

When I add a private deployed Azure Git Server in the Domain Registry, it can't detect that I'm using the azure as provider. Even if my remote url domain is `azure.mydomain.com`

I noticed that Azure is a hardcode domin, is this a bug or a requirement?
https://github.com/ben-gibson/GitLink/blob/ce69784b86c495ff0bd7c6e8d021a16cd3b9e955/src/main/kotlin/uk/co/ben_gibson/git/link/url/factory/AzureUrlFactory.kt#L11

**Comment by ben-gibson** [comment]
That's strange. I'm not sure why it can't auto-detect `Azure` given you've registered your custom domain. I'll take a look one evening this week.

**Comment by ben-gibson** [comment]
Could you share the output of `git remote -v` in your repo? You can anonymise the domain, I just want to see how the rest of it is structured.

**Comment by ben-gibson** [comment]
I couldn't reproduce this exactly, but I've made some improvement around Azure URL generation.
