### ISSUE TITLE
{banch} placeholder doesn't work as exptected

### ISSUE THREAD

**Issue by alexandertsukanov** [ben-gibson/GitLink#335]
Good afternoon!

I am trying to create a custom server, but I can't substitute the {branch} placeholder. It seems like GitLink ignores it when opening a commit. I am using the new Jetbrains UI.

here is the link I am using:
https://**bitbucket-server**/projects/someproject/repos/**repo**/browse/{file:path}/{file:name}?at=refs%2Fheads%2F`{branch}`

IC-242.20224.419, JRE 21.0.3+13-b509.4x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.0, screens 2992x1934 (200%); Retina

<img width="1384" alt="CleanShot 2024-09-01 at 13 33 05@2x" src="https://github.com/user-attachments/assets/cae89e9a-caba-4d76-9b03-d8dfe5a918cd">

Thanks.

**Comment by ben-gibson** [comment]
This should be fixed in `4.5.0`
