### ISSUE TITLE
Azure links are broken

### ISSUE THREAD

**Issue by murlakatam** [ben-gibson/GitLink#344]
gitlink 4.5.1
![image](https://github.com/user-attachments/assets/3cd1ac53-6ebc-44aa-9b35-f9e04e801996)

gitlink generates the following url
https://dev.azure.com/<org_name>/<project_name>/_git/<repo_name>.git?version=GBmain&path=correct.filepath&line=18&lineEnd=22&lineStartColumn=1&lineEndColumn=1

however correct url should not have the trailing `.git` in repo_name
https://dev.azure.com/<org_name>/<project_name>/_git/<repo_name>?version=GBmain&path=correct.filepath&line=18&lineEnd=22&lineStartColumn=1&lineEndColumn=1

![image](https://github.com/user-attachments/assets/be28c940-59f5-4f15-bae9-72a6b5fa1fd8)

**Comment by murlakatam** [comment]
tried both http and ssh based repos

**Comment by kyleratti** [comment]
I am seeing this too! All of my Azure DevOps links have that same `.git` suffix on the repository. Dropping that suffix makes the link work.

**Comment by kyleratti** [comment]
It looks like this regressed on c56b7084c2f529534a3a36a380e9e8ca60c566d3.

**Comment by ben-gibson** [comment]
Oh, I thought `.git` was required for Azure links (it is on my dummy repository). I’ve reverted this part of the change, so it should be working again in `4.5.2`.

**Comment by kyleratti** [comment]
Thank you @ben-gibson! Seems resolved on my side in 4.5.2!
