### ISSUE TITLE
Generic URL Plugin

### ISSUE THREAD

**Issue by luckydonald** [ben-gibson/GitLink#44]
Hey, it would be awesome to be able to add your own url, like
`https://example.com:8080/{project}/{branch}/{commit}/{filepath}/{filename}#{linenumber}:{columnnumber}`

So you could basically build your own urls from variables like project, branch, commit hash, file path and/or line number.

**Comment by ben-gibson** [comment]
Yeah, that sounds nice, I will probably take a look in the next week or so.

**Comment by markiewb** [comment]
FYI: A similar pattern style chose I for my old NetBeans-plugin.

<img src="https://raw.github.com/markiewb/nb-git-open-in-external-repoviewer/master/doc/1.5.0.png"/>
https://github.com/Chris2011/nb-git-open-in-external-repoviewer

**Comment by ben-gibson** [comment]
@luckydonald could you test this new feature and let me know if it works as you expect. I have attached the currently unreleased version of the plugin (2.1.0). You can install the plugin from Preferences → Plugins → Install plugin from disk.

[GitLink-2.1.0.zip](https://github.com/ben-gibson/jetbrains-open-in-git-host/files/1444127/GitLink-2.1.0.zip)

**Comment by ben-gibson** [comment]
This has been done in version 2.1.0

**Comment by luckydonald** [comment]
Will have a look, sure!

**Comment by luckydonald** [comment]
Awesome!

Would it be possible to have the `{commit}` available in the file template, too?
Usecase: Permanent links
Also for completeness sake, is there a `{column}`?
