### ISSUE TITLE
Permalink for custom links

### ISSUE THREAD

**Issue by luckydonald** [ben-gibson/GitLink#56]
#44 is really awesome!

Would it be also possible to have the latest `{commit}` available in the file template, too?
The usecase would be to export permanent links.

Also for completeness sake, is there a `{column}`?

**Comment by luckydonald** [comment]
Also, 
the current syntax is 
```css
https://example.com:8080/foobar/{branch}/{filepath}/{filename}#{line}
```
I realized if you look at files on the root, e.g. `.gitignore` you'll get pathes like
https://example.com:8080/foobar/master//.gitignore

So the question is, should the path end with a slash `/`?
```css
https://example.com:8080/foobar/{branch}/{filepath}{filename}#{line}
```

**Comment by ben-gibson** [comment]
This shouldn't be too difficult to implement, I will take a look sometime this week.

**Comment by luckydonald** [comment]
See #61

**Comment by luckydonald** [comment]
For the commit hash, a settable size would be an nice extra.
Two ideas: 

To limit it to e.g. `6` character we could either use a pull down,
or something in the templates like `{commit:6}`.

**Comment by ben-gibson** [comment]
This has been added in release `2.3.0`.
