### ISSUE TITLE
Add an action to open the file to the annotation context menu

### ISSUE THREAD

**Issue by markiewb** [ben-gibson/GitLink#57]
Add an action to open the file from the annotation context menu.

**Use-Case:** I tracked an issue down to its commit via the "blame"-sidebar ("Show annotations" in the context menu of the line gutter) and now I like to document this culprit line in a bug-tracker. Thus I like to copy the URL (or open the browser window and then copy the URL) to this file at the given commit. 

![image](https://user-images.githubusercontent.com/1857095/33516879-34a85e8e-d77a-11e7-8e91-d02e26975d6c.png) 

Make sure that 
* the commit/revision ID of the current hovered line in the annotation bar is used
* the line number of the current hovered line in the annotation bar is used (I am not sure, if this is possible )

**Comment by ben-gibson** [comment]
This has been added in release `2.3.0`.
