### ISSUE TITLE
Please add parameter for project name

### ISSUE THREAD

**Issue by rickthepick** [ben-gibson/GitLink#58]
We use Stash but the URL generated using the "Stash" host doesn't look like our setup.  Using "Custom" host I can get pretty close, e.g.,
https://stash.example.com/projects/fe/repos/cobalt/browse/{filePath}/{fileName}?at={branch}#{line}

but I have to hard code the project name ("cobalt") into the URL.  Can you create a "project" variable so I can do something like:
https://stash.example.com/projects/fe/repos/{project}/browse/{filePath}/{fileName}?at={branch}#{line}

The settings seem to suggest that the settings are per project, but in my testing there is just one set of settings for all projects:
![image](https://user-images.githubusercontent.com/328585/35163572-39661112-fd15-11e7-90be-a028cb1173bc.png)

**Comment by ben-gibson** [comment]
Hmm, strange. The settings should defiantly be on a per project basis. When I create a new project it doesn't carry over the settings I have applied in any of my other projects. Could you provide the following information:

- IDE & Version (PhpStrom 2017.3, Intellij 2017.3, Webstrom 2017.3 etc)
- OS
- Plugin version (should be shown at the bottom of settings page in your screenshot)
- The expected URL
- The actual URL
- The result of `git remote -v`

**Comment by rickthepick** [comment]
So this is what I've found.  The settings are one a per "project" basis, but do not work when you use RubyMine's File -> "Attach project..." (add an additional project to the window).  For example:  
![image](https://user-images.githubusercontent.com/328585/35237517-e832ff06-ff78-11e7-877f-3e1e4705e597.png)

Let's say I open project "x" and then attach projects "y" and "z" to the window.  So in the Project view I will see "x", "y" and "z".  These three projects are considered one project with respect to the GitLink settings.  For example, even though there are three projects in the window GitLink will use the settings for the "x" project - the first project opened.

If I open each project in a separate window (using RubyMine's File -> "Open...") it works as expected.

This is too bad since I'm not going to open each project in it's own window.  I mean what IDE forces that on you?  I guess IntelliJ does since IntelliJ does not have "Attach Project...".

Also this behavior almost certainly has nothing to do with GitLink and there is probably nothing that can be done about it.
