### ISSUE TITLE
Generates incorrect URL

### ISSUE THREAD

**Issue by Paitum** [ben-gibson/GitLink#59]
At my company we have a gitlab server. This plugin gets very close to generating the correct URL, except that it adds the remote name, "origin/" into the path.

Here is an example:
https://git.company.net/project/repo/blob/origin/master/dirA/dirB/file.js#15

and this is what works:
https://git.company.net/project/repo/blob/master/dirA/dirB/file.js#15

As a side note, when I use the gitlab web interface I see /tree instead of /blob.

Thanks for listening to my issue.

**Comment by ben-gibson** [comment]
Oh, interesting. Could you attach the output of the command `git remote -v` on your repository? You can replace the hostname with a pseudo one.

**Comment by ben-gibson** [comment]
Also, are you on the remote branch e.g. `origin/master` when this happens? If so could you confirm if it works when you checkout the local version?

**Comment by Paitum** [comment]
Found the problem. When responding to your two posts, it was working on a different repository... so I found a project that used HTTP instead of SSH, and that may have been the difference:

```
git remote -v
origin  https://git.company.com/project/repoName (fetch)
origin  https://git.company.com/project/repoName (push)
```

```
git remote set-url origin git@git.company.com:project/repoName.git
```

```
git remote -v
origin  git@git.company.com:project/repoName.git (fetch)
origin  git@git.company.com:project/repoName.git (push)
```

This repository is working with your plugin (and the other plugin I was using Git Integration). Thanks.
