### ISSUE TITLE
Does not work with non-standard name for remote

### ISSUE THREAD

**Issue by kool79** [ben-gibson/GitLink#60]
In my repo I dont have standard name for remote: 'origin' (I have 4+ remotes so I use meaningful names for them)
When I try to navigate to github i got error 
`GitLink(2.2.0): Could not find the remote 'origin'`

Please note that standard plugin from IntelliJ (`GitHub` plugin)  works good with such names. But standard plugin works only with github (I need gitlab also).  Maybe you can see how it is implemented in IntelliJ and use the similar approach.

  BTW, plugin from IntelliJ also implemented  feature from https://github.com/ben-gibson/GitLink/issues/57 but again, for repos located on github only

**Comment by ben-gibson** [comment]
This could probably be a new configuration option, defaulting to origin. I will try to get that added soon.

**Comment by ben-gibson** [comment]
This has been added in release `2.3.0`.
