### ISSUE TITLE
Please add option to open permanent link

### ISSUE THREAD

**Issue by l0co** [ben-gibson/GitLink#61]
It would be useful to have an option in plugin settings to open by default not a version from given branch, but the version from current commit. The same what is available in GitLab after clicking "Permalink".

The example for GitHub:

- https://github.com/ben-gibson/GitLink/blob/master/LICENSE - branch link
- https://github.com/ben-gibson/GitLink/blob/3843271518a66d51b7a8d1e6a3c70962a4561c52/LICENSE - permanent link

Only using permanent link you can be 100% sure that someone who receives the link will see exactly what you assumed, because in the meanwhile the file may change in given branch. For the same reason this is usueful for putting links with references to source code in documentation.

**Comment by ben-gibson** [comment]
This is something that has come up in a few other issues too. I’m most of the way through making the adjustments for it already. Going forwards it will use the commit unless it doesn’t exist on the remote in which case it will fallback to the branch.

**Comment by l0co** [comment]
Great :)

**Comment by luckydonald** [comment]
Maybe for the normal plugins a `permalink` checkbox would be a great idea, replacing the branch name with the commit hash.

**Comment by luckydonald** [comment]
@ben-gibson Awesome this is happening!

**Comment by ben-gibson** [comment]
This has been added in release `2.3.0`.

**Comment by l0co** [comment]
I'm working now on some yet-another-wiki-page in my project and the new feature works like a charm :)

**Comment by ben-gibson** [comment]
Don't forget to rate https://plugins.jetbrains.com/plugin/8183-gitlink 😉

**Comment by l0co** [comment]
Done ;)

**Comment by l0co** [comment]
@ben-gibson Have you changed something recently in this feature? Because somehow it stopped working in my IDE either after plugin or idea update.

**Comment by ben-gibson** [comment]
I don't think so, it should still work. The only reason it wouldn't use the commit is if it didn't exist on the remote i.e. it hadn't been pushed yet. In that situation it would fallback to generating a link to the file at HEAD.
