### ISSUE TITLE
Also add context menu to line number column

### ISSUE THREAD

**Issue by luckydonald** [ben-gibson/GitLink#62]
![image](https://user-images.githubusercontent.com/2737108/36588486-8ad3cc4a-1888-11e8-966f-2f63d6894eb5.png)

I way to often try to do it this way, as you mark the line number in git{hub,lab} by clicking on those numbers.

Could we get this supported, or would that require too much work?

**Comment by luckydonald** [comment]
Issue #57 seems to be related, as it more or less uses the same column.

**Comment by ben-gibson** [comment]
This has been added in release `2.3.0`.
