### ISSUE TITLE
GitBlit support for "Open file at commit"

### ISSUE THREAD

**Issue by ben-gibson** [ben-gibson/GitLink#65]
@markiewb is this something you could add?

https://github.com/ben-gibson/GitLink/blob/master/src/uk/co/ben_gibson/git/link/Url/Factory/GitBlitUrlFactory.java#L101
https://github.com/ben-gibson/GitLink/blob/master/src/uk/co/ben_gibson/git/link/Url/Factory/GitBlitUrlFactory.java#L151
https://github.com/ben-gibson/GitLink/blob/master/tests/unit/uk/co/ben_gibson/git/link/test/Url/Factory/GitBlitUrlFactoryTest.java#L119

**Comment by markiewb** [comment]
@ben-gibson: I will, but not in an instant. Within the next two weeks sounds realistic.

**Comment by markiewb** [comment]
Ok. I implemented it. It gave me no rest. Please review the pending PR!
