### ISSUE TITLE
Add 'open commit' to annotate menu

### ISSUE THREAD

**Issue by doekenorg** [ben-gibson/GitLink#70]
We use the feedback tool in gitlab to peer-review the code. Only place this is possible is in the actual commit. 

When browsing the code you can open the annotate menu, and see who did what, and when. It would be super useful if we can also open the commit directly from that menu, instead of opening the git log, and then clicking the 'open commit' link. 

I think it's a small tweak, but it would really help with productivity.

**Comment by ben-gibson** [comment]
Which version are you running? I think what you're asking for was already added in #57

**Comment by doekenorg** [comment]
I'm using version 2.3.1. And although it seems similar, it's not quite the same. #57 focuses on the file itself, opening a link to the blob. I'm asking for a link to the actual commit. It's the same link as 'open commit in github' in the git log menu. 

![open-commit-gitlab](https://user-images.githubusercontent.com/529515/41286170-cd1b8d2a-6e3e-11e8-81e0-443985ae53ab.png)

**Comment by ben-gibson** [comment]
Ah, make sense. I will try and get that added later on this week.

**Comment by doekenorg** [comment]
HI @ben-gibson, 

Was just wondering if there was any progress on this issue. Thanks!

**Comment by ben-gibson** [comment]
Hello, I have pretty much done this now. I'm just wondering if you ever use the copy link option as I'm considering removing it to simplify the number of available options?

**Comment by doekenorg** [comment]
No not really. I can always copy the link from the browser. But I've never used it. 

Thanks for this update!

**Comment by ben-gibson** [comment]
Done.
