### ISSUE TITLE
Change Port Number

### ISSUE THREAD

**Issue by TildBJ** [ben-gibson/GitLink#71]
Would be great if there would be a possibility to change the Port number vor the GitLink.

**Comment by pedromartinez11** [comment]
You can make a custom configuration for this.
See the wiki: https://github.com/ben-gibson/GitLink/wiki/Custom-Host

**Comment by tsvsj** [comment]
The `{remote:url}` doesn't contain the port from the remote configuration. In my case I use Gitea on Port 3000. This seems not to work, although the port is set on the remote URL and Phpstorm is able to push commits correctly.

**Comment by ben-gibson** [comment]
You could hardcode the port number in this case e.g. `{remote:url:host}:3000/foo/bar`
