### ISSUE TITLE
support for "Open file at branch"

### ISSUE THREAD

**Issue by yhan219** [ben-gibson/GitLink#72]
Before version 2.2.0,it is open file at branch. But then it became "at commit".So i think you can make a control switch in the settings for the user to choose which one to use

**Comment by minidmnv** [comment]
Maybe it should be in this two places? Not only in one.

I can look into it. Just tell me what You think about this idea.

**Comment by holgerbrandl** [comment]
It would be awesome if the "open at head revision" in the current branch would be brought back. For instance, my main use-case is that I want to get links to specific repo files to send them to colleagues. There, my coworkers and I do not mind the specific commit but rather need a pointer to the head revision of a file in the current branch.
