### ISSUE TITLE
Use https in generated links

### ISSUE THREAD

**Issue by oowekyala** [ben-gibson/GitLink#74]
It would be nice if the generated links used https. For example, links to a line are rendered as a preview in Github, but only if the protocol is https (and the commit reference is absolute).

https://github.com/ben-gibson/GitLink/blob/4a8cbac2eda1a68cc348b11c19b4d17248230eee/src/uk/co/ben_gibson/git/link/Container.java#L25-L26

but 

http://github.com/ben-gibson/GitLink/blob/4a8cbac2eda1a68cc348b11c19b4d17248230eee/src/uk/co/ben_gibson/git/link/Container.java#L25-L26

**Comment by ben-gibson** [comment]
There’s a Force HTTPS option in the settings that should do what you need. Let me know if it works.

**Comment by oowekyala** [comment]
@ben-gibson Oh yes that's exactly what I'm looking for, thanks :)
