### ISSUE TITLE
Support for multiple vcs root on same project with custom Url

### ISSUE THREAD

**Issue by lcsdms** [ben-gibson/GitLink#75]
Hi! 
I really like the plugins, but I'm having some problems , with a single project that has multiple VCS roots inside: 

I have a custom repository (self hosted gitlab) with multiple VCS roots inside the same project.

In the custom url config there's only variables for {branch}, {file}, commit, etc, but there's not variable referencing the specific VCS project inside the url.

Is there a way to achieve what I'm trying to do here ? 

Thanks!

**Comment by lcsdms** [comment]
This looks like it's related to [this issue](https://github.com/ben-gibson/GitLink/issues/58)

**Comment by ben-gibson** [comment]
Do you need to use the custom host type? The GitLab host should work even if there's multiple VSC roots in the same project. Either way it would be pretty simple to add placeholders like `{remote-path[0]}` and `{remote-path[1]}` to the custom type which I think would give you what you need e.g. `https://example.com/{remote-path[0]}/{remote-path[1]}/commit/{commit}` which in the case of this repository would result in `https://example.com/ben-gibson/GitLink/commit/e53gt`

**Comment by lcsdms** [comment]
@ben-gibson  thanks for the response! 
I'm trying to use using custom host because it's a self hosted gitlab instance, with custom url. But I just assumed that would only work with gitlab hosted on the cloud with gitlab url, BUUUUUT...

Just tested now selecting gitlab and it worked, even with multiple VCS on the same project =P

I'll be closing the issue then, since all the VCS roots and gitlab are working perfectly.

Thank you very much for your time and the plugin!

**Comment by DanaGoyette** [comment]
I'd like to have this as well, for an IntelliJ project that contains multiple git roots, and none of them are on the supported providers.

Example of a git URL and the corresponding web URL:
Git Remote: https://chromium.googlesource.com/chromiumos/third_party/autotest
File Path: README.md
Web URL: https://chromium.googlesource.com/chromiumos/third_party/autotest/+/master/README.md#1

To support multiple such roots with different git projects, I'd need something like this:
https://chromium.googlesource.com/chromiumos/{project}/+/{branch}/{filePath}/{fileName}#{line}
