### ISSUE TITLE
Autodetect Host Type

### ISSUE THREAD

**Issue by mrh1997** [ben-gibson/GitLink#76]
We do not check our Intellij Projects in. That means everytime I check the repo out, I have to setup the .idea project again. It would be nice if I would not need to setup getlink, too.

Wouldn't it be possible to detect the kind of repository automaticially? (I assume that GitHub, GitLab, Bitbucket have different APIs; so by checking the API it should be possible very fast to check what kind of host is used)

**Comment by caugner** [comment]
Maybe for your use case it would help, if it was possible to modify the global default value for the `Hosts` field.

**Comment by ben-gibson** [comment]
Yeah I like that idea, the other option would be to have an `Auto Detect` host type that's selected by default. This could inspect the remote URL associated with the file or commit being opened on the fly and figure out the host. However this would only work when the domain is not custom e.g. `github.com` and it would have to do this detection on every run.

**Comment by and-semakin** [comment]
For now I see that GitLink opens my files on GitLab properly event if I haven't changed host type (it's GitHub by default). The only issue that the menu entry is named "Open in GitHub" but opens GitLab. Why can auto detect host and open correct link but not rename menu entry?

**Comment by ben-gibson** [comment]
It's not building the correct URL through any kind of auto-detection it just happens to be that `GitHub` and `GitLab` use a _nearly_ identical URL structure. If for example, you changed the host type to something like `BitBucket Cloud` it would generate a completely incompatible URL and you would see a `404` response.

**Comment by rickthepick** [comment]
I would be very happy with a global default.  That way I would have to flip it to "Bitbucket Server" for every project.

**Comment by simonberger** [comment]
The global default would indeed be very helpful !
Another easier idea instead of the auto detection would be a list of host url to provider matching.

**Comment by gdubicki** [comment]
+1 to this too.

Without this feature this plugin is very cumbersome to use for me.

I am using many both GitLab and GitHub repositories and I cannot/do not want to commit the IntelliJ config to them.

So choosing the right repo type manually would be a lot of work.

And without the autodetection every time I use GitLab repo (which is configures as GitHub by default) and copy a link to a line of code it generates as:
```
http://gitlab.mycompany.com/.../file.txt#L11-L11
```
...which doesn't work in GitLab, so I have to manually correct it to:
```
http://gitlab.mycompany.com/.../file.txt#L11
```
Similarly multi-line link like:
```
http://gitlab.mycompany.com/.../file.txt#L11-L15```
```
...needs manual correction to:
```
http://gitlab.mycompany.com/.../file.txt#L11-15
```
...to work. :(
