### ISSUE TITLE
Possibility to mark a project as "non-git-based"

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ben-gibson/GitLink#79]
Hi! Thanks for this great plugin!

Is there a way to disable the plugin for projects that are not git-based? Or add an option to disable GitLink menu entries if no git repo is detected?

In svn-based projects the inconvenience is, of course, very minor, just a couple of menus that no longer work, but nevertheless=)

Cheers!

**Comment by ben-gibson** [comment]
Yeah having a disable button in the project configuration sounds useful. I will look at adding this in the next release.

**Comment by ben-gibson** [comment]
Released in `3.0.0`

**Comment by ShrykeWindgrace** [comment]
Great, thanks a lot!
