### ISSUE TITLE
Getting wrong Bitbucket URL

### ISSUE THREAD

**Issue by m2spring** [ben-gibson/GitLink#84]
Choosing "Bitbucket" host, the resulting URL is not what I expect it to be

I get:
```
https://bitbucket-eng-sjc1.example.org/~m2spring/myproj-core/src/eb4ef508363cf4e1e9350fa0a8be02cfe38e9f77/persistence/src/main/java/org/example/myproj/persistence/model/api/AttributeDetail.java#AttributeDetail.java-167
```

I want:
```
https://bitbucket-eng-sjc1.example.org/bitbucket/users/m2spring/repos/myproj-core/browse/persistence/src/main/java/org/example/myproj/persistence/model/api/AttributeDetail.java#167
```

Is there somewhere I can fine-tune the generated URL?

Thanks!

**Comment by ben-gibson** [comment]
Could you try selecting the host `Stash` which needs to be renamed to `Bitbucket server` (I will do that in the next release)

**Comment by m2spring** [comment]
With host `Stash` I get this:
```
https://bitbucket-eng-sjc1.example.org/projects/~m2spring/repos/dascode-core/browse/persistence/src/main/java/org/example/myproj/persistence/model/api/AttributeDetail.java?at=eb4ef508363cf4e1e9350fa0a8be02cfe38e9f77#167
```

Trying out the Custom URL option, I can make some more progress with this first approximation pointing to the authorative repository instead of my own fork (which is actually what I want): 
```
https://bitbucket-eng-sjc1.example.org/bitbucket/projects/DAS/repos/myproj-core/browse/{filePath}/{fileName}#{line}
```
But I'm missing placeholders for
* Bitbucket project ("DAS")
* Bitbucket repository name ("myproj-core")

What's the list of all supported placeholders?

Thanks!

**Comment by ben-gibson** [comment]
Moved into #92.
