### ISSUE TITLE
Missing functionality of copying link to clipboard

### ISSUE THREAD

**Issue by MalcolmK** [ben-gibson/GitLink#85]
Since one of the updates I'm missing the option to copy the link to the clipboard. It was introduced in https://github.com/ben-gibson/GitLink/issues/47 and it is a feature I am using very often. Is it possible to return this feature?

**Comment by FuegoFro** [comment]
@ben-gibson It looks like this was removed in https://github.com/ben-gibson/GitLink/commit/13b427d3c7a916d9572df5f0aa178d9fe65fb694. Is the intention that copying a link to a clipboard (without opening the browser) will not be a supported action moving forward? Would you be open to a PR that re-adds this functionality?

**Comment by ben-gibson** [comment]
It's not an action I personally used. I would normally just copy the URL from the browser if I needed it but I didn't really appreciate how much other people were using it. I'm not against adding it back in if it's something people still find useful though. One particular issue I had with it was the clutter it caused in menus like the one in the annotation gutter where two options exist i.e. `Open commit in GitHub` and `Open file in GitHub`. With the copy functionality this creates four menu items `Open commit in GitHub`, `Copy commit in GitHub`, `Open file in Github`, `Copy file in GitHub`. Potentially this could be solved using sub-menu that has a divider separating the clipboard and browser actions similar to this:

<img width="1103" alt="screenshot 2019-02-23 at 11 44 32" src="https://user-images.githubusercontent.com/1383604/53286052-97856280-3760-11e9-9064-7cb35f46f58c.png">

**Comment by MalcolmK** [comment]
That would be fine for me. The way it would be solved is not really an issue for me, since I would use the keystroke. My main concern is that is would be re-implemented.

**Comment by MalcolmK** [comment]
@ben-gibson Do you think you will solve this issue in the near future?

**Comment by MalcolmK** [comment]
@ben-gibson ...

**Comment by ben-gibson** [comment]
Yep the functionality will be re-added in the near future. I just haven't had time to work on it recently.

**Comment by MalcolmK** [comment]
@ben-gibson Do you have any idea when that (roughly ofcourse) will be?

**Comment by jchannon** [comment]
Just hit this too after upgrading to Rider 19.1, that menu item was exactly what I used this for, right click, copy link , paste in slack to co workers

**Comment by obriat** [comment]
This is so useful when you have to copy the commit in tickets or stories when you close them

**Comment by MalcolmK** [comment]
@ben-gibson Is it really that hard to put this stuff back?

**Comment by dschiera95** [comment]
This is the feature that led me to install this plugin in the first place. 
I use it to copy and send the link to co workers.

**Comment by ben-gibson** [comment]
This has been re-added in `3.3.0`
