### ISSUE TITLE
Improve substitutions for custom host type.

### ISSUE THREAD

**Issue by ben-gibson** [ben-gibson/GitLink#92]
A number of requests have been made to improve the substitutions available in the custom host type (see #91 #75 #84 #44 #56)

### Requirements

- Add substitution for short commit reference e.g. `{commit:short}`
- Add substitution for remote paths (in most cases the path contains the `project` and `repository` identifier however this is a host specific concept.
- Add a wiki page detailing the different substitutions with examples and link to it from the configuration.
- Potentially use this substitution system to generate the URLs for the supported host types.

**Comment by ben-gibson** [comment]
Initial wiki page https://github.com/ben-gibson/GitLink/wiki/Custom-Host

**Comment by joshkaplan** [comment]
For `remote`, being able to reference the various parts (i.e. `remote:url:path:1`) make it more usable, since the desired link structure and the full remote path may not always line up. 

Example:
For the particular private remote hosts I'm working with, access to the `remote:url:path` would not be sufficient to create the desired url, whereas access to the various parts of the path would be.

**Comment by ben-gibson** [comment]
Yep that will be included as well.

**Comment by b1oki** [comment]
I still don’t understand how to write pattern for a commit:
`http://host:port/group/project/commit/d6ae5b968a6d286450c21047ea87ed5c7ca2775c`

Try pattern `http://host:port/{remote:url:path}/{commit}` and get error *GitLink 3.1.1*: `An unknown error occurred. 0x03000001`

**Comment by ben-gibson** [comment]
These changes haven't been released yet. They will be part of the upcoming 3.2.0 release.

**Comment by thughes** [comment]
Any update on the `{remote:url}` support described on the wiki?

https://github.com/ben-gibson/GitLink/wiki/Custom-Host

It's exactly what I need.

**Comment by ben-gibson** [comment]
This has been released in version `3.2.0`
