### ISSUE TITLE
Link to private repo in organization is invalid

### ISSUE THREAD

**Issue by ukayani** [ben-gibson/GitLink#94]
Hi, love the plugin. 
I'm having an issue however with links generated for repos within a github org that begin with digits.

For example, my org is 500px and lets say i have a repo named `test`

**Describe the bug**

**To Reproduce**
1. Clone a repo from an organization with name beginning with digits (ex. `500px`)
2. Open a file in editor, select a line
3. Click open in github
4. Generated link is  https://github.compx/test/...

**Expected behavior**
I expect the link to be https://github.com/500px/test...

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 12

**Comment by ben-gibson** [comment]
Thanks for reporting this issue. It seems to be mistakenly replacing this whilst removing the port from the remote URL.

**Comment by ben-gibson** [comment]
This has been fixed in release `3.1.2`.
