### ISSUE TITLE
Make check of existence of current commit on remote optional

### ISSUE THREAD

**Issue by rdavila** [ben-gibson/GitLink#97]
I'm using this plugin with a large project (above 120,000 commits and hundred of branches) and it is really slow when trying to opening a file. On the IDE I see the process is stuck with the message `GitLink - Opening file` which leads me to think that the culprit is [this line](https://github.com/ben-gibson/GitLink/blob/df5527bb3f249fc473caff64000be83f26971d93/src/uk/co/ben_gibson/git/link/GitLink.java#L71). I think would be nice if we can have the ability to disable this check.

**Comment by ben-gibson** [comment]
Internally this runs the command `git branch -r --contains <a-commit-hash>` to determine if the commit exists on the remote or not. How long does that take to resolve for you if you run it directly from your command line?

**Comment by rdavila** [comment]
@ben-gibson on a large project:
```
time git branch -r --contains 751d013e98fe15d78f576850436369521b515102

real    0m24.899s
user    0m24.803s
sys     0m0.085s
```

On a smaller one:

```
time git branch -r --contains fdeecc702f3fc5381548f924e32f4f2c1cd63882

real    0m0.106s
user    0m0.024s
sys     0m0.033s
```

**Comment by thughes** [comment]
Also having this issue when using the plugin with various repos in the Chrome OS source code (https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md#Get-the-Source)

**Comment by ben-gibson** [comment]
I will try and get this deployed tomorrow.

**Comment by ben-gibson** [comment]
Released.

**Comment by rdavila** [comment]
Thanks a lot @ben-gibson!
